environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      nodejs_version: Stable
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      nodejs_version: LTS
matrix:
  fast_finish: true

platform: x64
configuration: Release
skip_branch_with_pr: true

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version x86
  - ps: Add-AppveyorMessage "node version $((node --version).trim())"
  - ps: Add-AppveyorMessage "npm version $((npm --version).trim())"
  - ps: Add-AppveyorMessage "Package version $($env:pkg_version)"
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - npm install --ignore-scripts

build_script:
  - ps: Add-AppveyorMessage "Starting x86 build"
  - ps: Set-AppveyorBuildVariable -Name pkg_version -Value (node -p "require('./package.json').version").trim()
  - ps: Set-AppveyorBuildVariable -Name bundle_name -Value (node scripts\bundle.js).trim()
  - ps: Add-AppveyorMessage "Bundle name $($env:bundle_name)"
  - npm run build
  - 7z a -ttar %bundle_name%.tar out\lib out\src
  - 7z a %bundle_name%.tar.gz %bundle_name%.tar
  - appveyor PushArtifact %bundle_name%.tar.gz
  - ps: Add-AppveyorMessage "Artifact pushed $($env:bundle_name)"
  - ps: Add-AppveyorMessage "Starting x64 build"
  - ps: Install-Product node $env:nodejs_version x64
  - ps: Set-AppveyorBuildVariable -Name pkg_version -Value (node -p "require('./package.json').version").trim()
  - ps: Set-AppveyorBuildVariable -Name bundle_name -Value (node scripts\bundle.js).trim()
  - ps: Add-AppveyorMessage "Bundle name $($env:bundle_name)"
  - npm run build
  - 7z a -ttar %bundle_name%.tar out\lib out\src
  - 7z a %bundle_name%.tar.gz %bundle_name%.tar
  - appveyor PushArtifact %bundle_name%.tar.gz
  - ps: Add-AppveyorMessage "Artifact pushed $($env:bundle_name)"

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  release: v$(pkg_version)
  description: 'Unsigned release'
  provider: GitHub
  auth_token:
    secure: YXNTtjYu8cQ8OYNGZq+HwHhq5UOVxmKGDoZtTf+ahKBDy4Qw2Kfb46XUav/K8HDW
  draft: false
  prerelease: true
  on:
     branch:
      - master
     appveyor_repo_tag: true        # deploy on tag push only
